### ISSUE TITLE
Clean up logging timestamps for web worker

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-backend#74]
Right now, the logs on papertrail look like this:

 Jan 25 15:13:03 projectifyapp app/web.1 [2022-01-25 23:13:03 +0000] [11] [INFO] Application startup complete.

The second timestamp is unnecessary. It might be possible to remove it by tweaking the gunicorn logging settings

**Comment by apkallum** [comment]
The option `worker_log_format` does not work. I suspect we need to change the handler. See: https://www.distributedpython.com/2018/08/28/celery-logging/#strategy-1

**Comment by justuswilhelm** [comment]
This might work https://docs.celeryproject.org/en/latest/userguide/configuration.html#worker-log-format

**Comment by justuswilhelm** [comment]
I just noticed the comments for the two related GH issues are mixed up. This issue here should be discussing gunicorn, the other should be discussing celery
