### ISSUE TITLE
Clean up timestamp logs for worker dyno

### ISSUE THREAD

**Issue by justuswilhelm** [jwp-consulting/projectify-backend#75]
Right now the logs look like this:

```
 Jan 25 15:13:00 projectifyapp app/worker.1 [2022-01-25 23:12:59,889: WARNING/MainProcess] Secure redis scheme specified (rediss) with no ssl options, defaulting to insecure SSL behaviour.
```

The second timestamp is unnecessary. There must be a way to remove it

**Comment by apkallum** [comment]
Gunicorn provides a command line option for formatting the access log only: https://docs.gunicorn.org/en/stable/settings.html#access-log-format

**Comment by justuswilhelm** [comment]
I think we have to use https://docs.gunicorn.org/en/stable/settings.html#logconfig

**Comment by justuswilhelm** [comment]
Too complicated to fix for now
